/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    './src/app/**/*.{js,ts,jsx,tsx}',
    './src/app/(routes)/**/*.{js,ts,jsx,tsx}',
    './src/app/(marketing)/**/*.{js,ts,jsx,tsx}',
    './src/app/(dashboard)/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/lib/**/*.{js,ts,jsx,tsx}',
    './src/hooks/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    fontFamily: {
      heading: ['var(--font-heading)', 'serif'],
      body: ['var(--font-body)', 'sans-serif'],
      primary: ['var(--font-primary)', 'sans-serif'],
      secondary: ['var(--font-secondary)', 'sans-serif'],
    },
    // Add default spacing scale
    spacing: {
      px: '1px',
      0: '0px',
      0.5: '0.125rem',
      1: '0.25rem',
      1.5: '0.375rem',
      2: '0.5rem',
      2.5: '0.625rem',
      3: '0.75rem',
      3.5: '0.875rem',
      4: '1rem',
      5: '1.25rem',
      6: '1.5rem',
      7: '1.75rem',
      8: '2rem',
      9: '2.25rem',
      10: '2.5rem',
      11: '2.75rem',
      12: '3rem',
      14: '3.5rem',
      16: '4rem',
      20: '5rem',
      24: '6rem',
      28: '7rem',
      32: '8rem',
      36: '9rem',
      40: '10rem',
      44: '11rem',
      48: '12rem',
      52: '13rem',
      56: '14rem',
      60: '15rem',
      64: '16rem',
      72: '18rem',
      80: '20rem',
      96: '24rem',
    },
    extend: {
      colors: {
        // New design system colors
        'primary-navy': 'var(--color-primary-navy)',
        'text-dark': 'var(--color-text-dark)',
        'text-light': 'var(--color-text-light)',
        'link-blue': 'var(--color-link-blue)',
        'success-green': 'var(--color-success-green)',
        'light-gray': 'var(--color-light-gray)',
        
        // Existing colors
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        buyer: 'var(--buyer)',
        seller: 'var(--seller)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
      },
      fontSize: {
        'h1': ['var(--text-h1)', { lineHeight: '1.2' }],
        'h2': ['var(--text-h2)', { lineHeight: '1.3' }],
        'h3': ['1.75rem', { lineHeight: '2.25rem' }],
        'h4': ['1.5rem', { lineHeight: '2rem' }],
        'body': ['var(--text-body)', { lineHeight: '1.6' }],
        'nav': ['var(--text-nav)', { lineHeight: '1.4' }],
      },
      fontWeight: {
        'light': 'var(--font-weight-light)',
        'regular': 'var(--font-weight-regular)',
        'medium': 'var(--font-weight-medium)',
      },
      borderRadius: {
        'default': 'var(--radius-default)',
      },
      boxShadow: {
        'widget': '0 2px 8px rgba(0,0,0,0.08)',
        'card': 'var(--shadow-card)',
      },
      minHeight: {
        'widget': '480px',
      },
      zIndex: {
        'modal': '1000',
      },
    },
  },
  plugins: [],
};
